### PR TITLE
Updated docs to follow Google markdown style guide

### PR DESCRIPTION
**Pull request by mikewalch**
* Set line limit to 100 chars
* Removed two spaces after period
* Removed trailing line spaces
* Converted all headings to ATX style

### CODE REVIEW

**Comment by keith-turner** [comment]
Was a tool used to do this formatting?

**Comment by mikewalch** [comment]
I used Intellij to have 100 char margin but it was done by hand.

**Comment by ctubbsii** [comment]
+1

**Comment by keith-turner** [comment]
+1

**Pull request merged**
