### PR TITLE
Found and fixed two bugs while working on the Fluo Tour.

### PR DESCRIPTION
**Pull request by keith-turner**
* Threads were not shutting down
 * Multiple collisions of non trigger node was failing in commit

### CODE REVIEW

**Comment by mikewalch** [comment]
The changes look good to me.  Do you know why tests are failing?

**Comment by ctubbsii** [comment]
If you mean Jenkins, it's been having a lot of problems lately, like not being able to resolve dependencies, etc.

**Comment by mikewalch** [comment]
I was talking about TravisCI which looks like it has tests that are failing and not dep issues.

**Comment by keith-turner** [comment]
I was able to run mvn verify 3 times successfully against this branch.   I am not sure why that test failed, I opened an issue to look into it.

**Comment by mikewalch** [comment]
+1

**Pull request merged**
