### PR TITLE
Deleted AUTHORS file, added NOTICE file, and removed 'incubator' from…

### PR DESCRIPTION
**Pull request by mikewalch**
… links to project website

### CODE REVIEW

**Comment by joshelser** [comment]
Don't forget about the DISCLAIMERS file with the necessary notification that fluo isn't a TLP (but an on-going effort in the ASF incubator)

http://incubator.apache.org/guides/branding.html

**Comment by joshelser** [comment]
e.g. https://github.com/apache/incubator-slider/blob/master/DISCLAIMER

**Comment by joshelser** [comment]
Looks great! Thanks @mikewalch

**Comment by mikewalch** [comment]
Cool.  Added DISCLAIMERS file in 78447d2953434

**Comment by keith-turner** [comment]
+1

**Pull request merged**
