### PR TITLE
Fixes #707 - Update versions for 1.0.0 release

### LINKED ISSUE #707: Update documentation for 1.0.0 version number.
Need to update Fluo's documentation for 1.0.0.   Like in some places the fluo 1.0.0-beta2 tar ball is mentioned.

### PR DESCRIPTION
**Pull request by mikewalch**
* Updated poms, config, and documentation

### CODE REVIEW

**Comment by ctubbsii** [comment]
That's a long subject line for a commit message :) Even GitHub had to wrap it into the comments of the PR.

**Comment by mikewalch** [comment]
@ctubbsii, should I change the version prefix to `1.0.0-incubating`? The poms could be `1.0.0-incubating-SNAPSHOT` until its released.

**Comment by ctubbsii** [comment]
@mikewalch I think that would work.

**Comment by mikewalch** [comment]
I set poms to `1.0.0-incubating-SNAPSHOT` and docs to `1.0.0-incubating`.

**Pull request merged**
